name: Build File Manager

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Windows installer
        run: python build_windows.py
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: output/FileManager-Setup.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          brew install create-dmg
      - name: Build macOS installer
        run: python build_macos.py
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-installer
          path: output/FileManager.dmg

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y dpkg-dev
      - name: Build Linux package
        run: python build_linux.py
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-package
          path: output/filemanager_1.0.0_amd64.deb
          
  create-release:
    needs: [build-windows, build-macos, build-linux]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows-installer/FileManager-Setup.exe
            artifacts/macos-installer/FileManager.dmg
            artifacts/linux-package/filemanager_1.0.0_amd64.deb
          draft: true
          generate_release_notes: true 